### ISSUE TITLE
docnado has to use relative import for navtree module

### ISSUE THREAD

**Issue by yurymik** [HEInventions/docnado#13]
Docnado doesn't work out-of-the box: it crashes due to incorrect module import:
```
$ docnado --new
Traceback (most recent call last):
  File "/usr/local/bin/docnado", line 7, in <module>
    from docnado.docnado import main
  File "/usr/local/lib/python3.7/site-packages/docnado/docnado.py", line 48, in <module>
    from navtree import NavItem, parse_nav_string
ModuleNotFoundError: No module named 'navtree'

$ python3 --version
Python 3.7.1
```
According to [this](https://stackoverflow.com/questions/16981921/relative-imports-in-python-3) fix is very simple:
```
--- docnado.py  2018-11-09 11:03:52.058225941 -0800
+++ docnado.py   2018-11-09 11:03:46.182084852 -0800
@@ -45,7 +45,7 @@
 from markdown.inlinepatterns import LinkPattern, IMAGE_LINK_RE, dequote, handleAttributes
 from markdown.blockprocessors import HashHeaderProcessor

-from navtree import NavItem, parse_nav_string
+from .navtree import NavItem, parse_nav_string


 class MultiPurposeLinkPattern(LinkPattern):
```

**Comment by JohnHardy** [comment]
Thanks @yurymik for reporting this and providing the fix!  The new 1.0.4 version is pushed to PyPi.

Just out of interest, how did you find out about docnado?

@wilad and I will have to migrate our CI tests over from Gitlab to catch stuff like this in future.  The fix seems to stop us running it from the console `python docnado.py` 

```
PS C:\Users\....\Desktop\docnado\docnado> python .\docnado.py
Traceback (most recent call last):
  File ".\docnado.py", line 48, in <module>
    from .navtree import NavItem, parse_nav_string
ModuleNotFoundError: No module named '__main__.navtree'; '__main__' is not a package
```

Do you know how to run it as a module without using `setup.py` to install it?

https://stackoverflow.com/questions/6670275/python-imports-for-tests-using-nose-what-is-best-practice-for-imports-of-modul

**Comment by yurymik** [comment]
I was looking what's new static blog generator world and found [this list](https://github.com/myles/awesome-static-generators#documentation). Docnado have caught my eye as I've head about (and used) Pelican, Jekyll, Hugo, and others, but never about this one. Also, I prefer Python over Ruby or node.js, so decided to give it a try.

**Comment by JohnHardy** [comment]
Thanks, please let us know if you have any more feedback.
