### ISSUE TITLE
html deployment structure

### ISSUE THREAD

**Issue by geraldbaeck** [HEInventions/docnado#17]
Thanks for that great software. I would like to suggest restructuring the directory structure of how the html is generated. Currently the content is in the w directory. 

I would recommend to get rid of the w directory, which would make it possible to deploy to gitlab or github pages without having an additional directory. For example I currently have to use it like this https://geraldbaeck.gitlab.io/NFS/w/

New Structure:
home.html (and whatever folders are in docs)
-- assets
  -- fonts
  -- lib
  -- css

**Comment by JohnHardy** [comment]
Good idea, the `/w/` directory was always a bit messy & unnecessary.

@wilad what do you think the best way to implement it is?  I think we had a PR that created an `index.html` in the root of the exported directory, but this takes it further.

**Comment by 6uhrmittag** [comment]
I added a dirty workaround to depoly to GitHub pages - it’s just a quickfix if you really want to use GitHub pages:

I basically just add a index.html in root that redirects to /w: https://github.com/6uhrmittag/slashlog-website/blob/master/docs/index.html

To add this index.html I modified docnado, but it can also be done via travis that adds it via script (It should be possible to add a file to the generated directory before deployment)

My dirty modification:  https://github.com/6uhrmittag/docnado/commit/eb242011b5a7bd4279c5e876ed241912efe5d4e7

This breaks the function for usage without GitHub pages, so it shouldn’t be added without caution.

You can see my travis.yml that I use to deploy to GitHub pages here: https://github.com/6uhrmittag/slashlog-website/blob/master/.travis.yml

**Comment by JohnHardy** [comment]
I like your solution @6uhrmittag - its simple and avoids re-engineering the way the pages are exported.  Is it acceptable to you @geraldbaeck and @wilad?  If so, I'd like to integrate it.

**Comment by JamesHannon** [comment]
Fixed in https://github.com/HEInventions/docnado/pull/23 thanks to @6uhrmittag, will be included in next release
