### ISSUE TITLE
--find-broken-links method reports non web links as broken

### ISSUE THREAD

**Issue by geraldbaeck** [HEInventions/docnado#18]
The function reports mailto: and tel: links probably everything except http and https

**Comment by JohnHardy** [comment]
Thanks for the report!

I think it is worth attempting to validate telephone number and email address formats.  

If these non-http external links validate, should we try to check its an active email address (can we?) or simply print out a note to manually check in a warnings section?

**Comment by geraldbaeck** [comment]
I would exclude them from checking there is no easy way to check for valid emails and surely not for valid phone numbers

**Comment by JamesHannon** [comment]
fixed in https://github.com/HEInventions/docnado/pull/22, will be included in the next release
