### ISSUE TITLE
Pages not "active" after setting weight for nav metadata

### ISSUE THREAD

**Issue by lblakej** [HEInventions/docnado#19]

**Comment by lblakej** [comment]
Applying weights to the nav metadata prevents the ```fa-circle-thin``` from changing to the ```fa-circle``` when that page is active.

For example:

```
nav:        Planning>Competition __2__ 
```

**Comment by JohnHardy** [comment]
Thanks for the bug report.  We will take a look! 👍

**Comment by JamesHannon** [comment]
fixed in above MR, will be released in next version
