### ISSUE TITLE
#nav- id contains whitespaces

### ISSUE THREAD

**Issue by geraldbaeck** [HEInventions/docnado#20]
The generated #nav ids do contain whitespaces, which provokes html validation errors.

https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fgeraldbaeck.gitlab.io%2FNFS%2Fw%2Ftheorie%2Fnotfaelle%2Ftoxisch%2Fco2-vergiftung.html

**Comment by JamesHannon** [comment]
fixed in https://github.com/HEInventions/docnado/pull/24, will be included in next release
