### ISSUE TITLE
Option to bind to alternate host

### ISSUE THREAD

**Issue by shawn-bandy-urbag** [HEInventions/docnado#21]
Similar to the --port argument, would it be possible to add an option to bind to another host (e.g. 0.0.0.0 rather than 127.0.0.1)?

**Comment by JohnHardy** [comment]
Good idea. We will add it to our job board (take a week or two) or happy to review a PR. Cheers!

**Comment by JamesHannon** [comment]
Solved in https://github.com/HEInventions/docnado/pull/25, this will be included in the next release

**Comment by shawn-bandy-urbag** [comment]
This is awesome - thanks so much.
