### ISSUE TITLE
Feature - add injectable CSS

### ISSUE THREAD

**Issue by JohnHardy** [HEInventions/docnado#29]
**Proposal**: add a metadata tag that injects HTML / CSS from a file into a page.  

**Rationale**:  The default style is great. However, there are times where, in a single page I would like to adapt it.  For instance, in a report it is nice to have numbered headings but NOT worth adding a `style` directory as is current best practice for theme-ing.

**Implementation**:

In the meta-data, look for a string array called `inject`

```
inject:  file.html 
       file.css
```

Then the template rendered can inject the contents of those files into the page directly, or in the case of css, inside a `<style>` tag.

**Use Case**:  For reference, the following adds numbered AND collapsible headings.
```
<style>
body {
    counter-reset: h2counter;
}
h1 {
    counter-reset: h2counter;
}
h2:before {
    content: counter(h2counter) ".\0000a0\0000a0";
    counter-increment: h2counter;
    counter-reset: h3counter;
}
h3:before {
    content: counter(h2counter) "." counter(h3counter) ".\0000a0\0000a0";
    counter-increment: h3counter;
}
</style>
<script type="text/javascript">
$(document).ready(function(){
    $("h2").click(function(){
    	$(this).nextUntil("h2").toggle()
    });    
});
</script>
```

Currently, this would have to be manually placed in every file.

**Comment by JamesHannon** [comment]
resolved in latest release
