### ISSUE TITLE
Table of Contents seems to be incorrect ordering

### ISSUE THREAD

**Issue by dlbradford** [HEInventions/docnado#42]
Hi,

I am just getting into the docnado tool, and really like it.

I am having a problem in ordering in the TOC on the left side of the page.

The ordering for my pages on output is:
3. Create Digital Bandwidths
2. SDH Data Modeling
1. Introduction
4. EAI Modeling

In the example above, I've inserted the numeric order for clarity

I *want* the ordering to be:

1. introduction.md:nav:                        Document__1__>Introduction
2. modeling-sdh-data-model.md:nav:             Document__2__>SDH Data Modeling
3. create-digital-bandwidths.md:nav:           Document__3__>Create  Digital Bandwidths
4. inventory_modeling_exercise_06.md:nav:      Document__1001__>Iventory Modeling

In the example above, I've also prepended the order I wish the items to be for illustrative purpose.

In the 'nav:' metadate entry listed at the end of the lines above, you can see I've tried to indicate desired order manually.

I hope my explanation is clear enough to understand.

Maybe you can spot something I've done stupid whilst trying to force the order I desire.

Thank you.

**Comment by JohnHardy** [comment]
Thanks for the report! We will attempt to reproduce and get back to you asap. Glad you like Docnado so far!

**Comment by dlbradford** [comment]
Glad to help with this. 
Additional information: After adding a fair amount of documents and following the ordering documentation, it seems the ordering is more or less random. Maybe some function got commented out or left out?

**Comment by ghost** [comment]
Hi dlbradford. Sorry it has taken so long to get to your ticket.

I have managed to recreate the issue that you have presented, it appears that our docs haven't properly explained the ordering feature, we will correct this in the next major patch :)

The nav-weight metadata should be appended to the *end* of the item you wish to sort.  In order for items to appear in the order you have suggested you should replace the nav: strings in each file with the following:

```
    introduction.md:nav: Document>Introduction__1__
    modeling-sdh-data-model.md:nav: Document>SDH Data Modeling__2__
    create-digital-bandwidths.md:nav: Document>Create Digital Bandwidths__3__
    inventory_modeling_exercise_06.md:nav: Document>Iventory Modeling__1001__
```

Again I apologise for the delay and I hope the answers your query. Don't hesitate to ask if you have any further issues.

**Comment by dlbradford** [comment]
Hi wilad,

Thanks for the update, no worry about the interval. Your reply has potentially saved me from migrating to another document solution which I was frankly not looking forward to.

I will test out the method you outline above, and hopefully it will address my issue.

Thanks again!

**Comment by ghost** [comment]
I have also revised the way that items are ordered by default.

Previously, when not explicitly ordered, nav items could be rendered in an unpredictable order. This was due to their references being stored in an unordered data structure under the hood (Dict).

They now, by default, render in alphabetical order unless explicit ordering is specified.

This feature should be in the next release.
