### ISSUE TITLE
search feature is missing

### ISSUE THREAD

**Issue by dartie** [HEInventions/docnado#46]
Please, it would be useful to add a search feature. Thanks

**Comment by JohnHardy** [comment]
Good idea!

For it to work offline/statically we would need to compute a tree / cache file that we can look through in JS. We'd need to compute this tree based on pages that have been rendered and resolved all links / injections (like CSV tables).

You thinking the search bar in the top bar, top of the nav menu, or somewhere different?

**Comment by dartie** [comment]
Hi John, 
thanks for considering it!
I was thinking about a search box in the nav (at the right side of the collapse/expand sidebar button).
Alternatively, you can create 2 different search boxes:
1) in the sidebar which filters for the title
2) one in the nav bar as above described for looking into the content

the first is quite easy I believe, I did one similar for a project of mine, which hides/shows element in the list on typing.

**Comment by JohnHardy** [comment]
Good point about title only search. I'll consider both options and the time it will take and reply back here. :)
