### ISSUE TITLE
Implement anchor tags so you can link to a heading/subheading in a document

### ISSUE THREAD

**Issue by JamesHannon** [HEInventions/docnado#54]
A potentially useful feature for the future, similar to gitlab Implement anchor tags so you can link to a heading/subheading in a document

**Comment by ghost** [comment]
Docnado already has this feature! When you create a heading e.g.:
`## This Is A Heading`

Creates a dash seperated ID related to that heading e.g. `this-is-a-heading`.

This can be linked to with `[Link Text](#this-is-a-heading)`
