### ISSUE TITLE
List markdown after the first indent appears to not be using an icon

### ISSUE THREAD

**Issue by General-101** [HEInventions/docnado#55]
![list markdown icon](https://user-images.githubusercontent.com/23564623/101739355-02ff0800-3a8d-11eb-9f65-667602b246f5.png)

```
	* Bone 1

		* Head

			* X: ```32.109``` Y: ```-5.0``` Z: ```0.0```

		* Tail

			* X: ```32.109``` Y: ```-4.0``` Z: ```0.0```

	* Bone 2

		* Head

			* X: ```-32.109``` Y: ```-5.0``` Z: ```0.0```

		* Tail

			* X: ```-32.109``` Y: ```-4.0``` Z: ```0.0```
```

**Comment by JohnHardy** [comment]
Hi!  What is the behaviour you would expect?  The circle ? to be replicated for the different multi-level lists or different bullets?  Please could you share an image to help me understand?

**Comment by General-101** [comment]
![101739355-02ff0800-3a8d-11eb-9f65-667602b246f5](https://user-images.githubusercontent.com/23564623/101946482-a0a12700-3bb4-11eb-9a0f-460f2769bec2.png)

This is a mockup image of what I would basically expect. Just for the circle to be replicated.

**Comment by ghost** [comment]
Hi General 101,
We try not to be too spesific with the stying and leave it up to users to decide things like this. Your issue can be solved on a per page basis by injecting a html style tag at the top of your page (after the metadata heading). e.g.

```
title:      Sample Page
desc:      sample page
date:       2020/12/15
version:    1.0.0
template:   document
nav:         Halo 1 __-1__>H1 Model Guides __3__>H1 JMS __0__>H1 Export __0__>My First H1 Model __10__
percent:    100
authors:    person@email.com

<style>
ul {
  list-style-type: circle;
}
</style>

# Overview

1. THis is an item

    * Bone 1

        * Head

            * X: ```32.109``` Y: ```-5.0``` Z: ```0.0```

        * Tail

            * X: ```32.109``` Y: ```-4.0``` Z: ```0.0```

    * Bone 2

        * Head

            * X: ```-32.109``` Y: ```-5.0``` Z: ```0.0```

        * Tail

            * X: ```-32.109``` Y: ```-4.0``` Z: ```0.0```

```

results in:
![image](https://user-images.githubusercontent.com/42382281/102207574-3646fa00-3ec6-11eb-9903-89a78241d66a.png)

___

You can also create your own template that implements this, if you start by duplicating our "document" template as a starting off point and modify the CSS from there.

___

You can also create a html page that implements your style changes and inject them at the start of each document. To do this refer to the "HTML Embedding" section in the documentation.

___

Thanks for your feedback. If you have any more questions don't hesitate to ask :)
