### ISSUE TITLE
Metadata not support utf-8

### ISSUE THREAD

**Issue by eduardocp** [HEInventions/docnado#7]
The value of a metadata is not currently rendered correctly if it has utf-8 characters.
This is because when opening the file on line 416, the encoding is not passed.

**Comment by ghost** [comment]
Hi eduardocp, thanks for your bug report.

I'm struggling to reproduce your error, can you send me a sample of the metadata string that's causing problems for you?

**Comment by eduardocp** [comment]
Of couse!

title:              MultiVendas
desc:             Módulo de Automação Comercial do MultiClubes
date:             2018/10/31
version:         1.0.0
template:      document
nav:               Home
percent:        100
authors:        eduardo_carisio@hotmail.com

**Comment by ghost** [comment]
Hi eduardocp, this is now solved and merged. It's awaiting deployment to the next release.

Thanks for your feedback!
