### ISSUE TITLE
Concatenate all sub-document in 1st nav-entry [Feature request]

### ISSUE THREAD

**Issue by 6uhrmittag** [HEInventions/docnado#9]
Currently the 1. nav-level doesn't show content and it's only purpose is to trigger the collapse.
It would be great to be able to generate one page(in the nav-bar) that contains all content of its sub-documents. This way the top level nav-entry shows an overview of all its sub-items. This could also be used as a simple blog.

Example menu:
- short-stories(shows "first short-story"+"second short-story")
  - first short story
  - second short story
- blog (shows content of today+yesterday)
  - today
  - yesterday
- Document
  - Text styles

Ideally there could be a switch to only show the 1. level nav-entry(and the content), but not the sub-items in the nav-bar(to not show 50 blog nav-entries)

**Comment by ghost** [comment]
Hi 6uhrmittag,
Thank you for your feedback.  Just out of curiosity, how did you hear about Docnado? :) 

I don't quite understand the feature you're asking for. Are you looking to use Docnado as a blogging platform, would you prefer it if all sub-documents appeared in a single large page when you click on each heading in the nav?

Could you give an example of where you would see the switch?  i.e. env variable or as part of the metadata?

**Comment by 6uhrmittag** [comment]
>  would you prefer it if all sub-documents appeared in a single large page when you click on each heading in the nav?

Yes, exactly. Sorry for the confusion :D 

It's much easier to have e.g. 15 short files with blog-entries and one file, that indicates that this directory is a blog rather than putting everything in one large file.
So, not a full blog, just a simple blogging-like feature. My usecase would be one nav-entry for a e.g. project-diary or a collection of "Today I learned"-entries.
(An advanced feature could be to have a metadata-key "frontpage" and a frontpage-template that lists all documents that are tagged with "frontpage"... but a simple diary would be a great start.)

I imagine something like this:

```
def _render_markdown:
  template = md.Meta.get('template', None)
  if template == blog-index:
     doc_files = glob.iglob(./*.md', recursive=True) #get all files in the current file's directory
     blogEntries = createBlogEntrys(doc_files) #create a list of entries and meta
      return render_template(template=blog-index, entryList=blogEntries)
```

in style/templates/blog-index.html:
```
  #the usual jinja template
  {% for entry in entryList %}
        {{ entry.meta }}
        {{ entry.title }}
  {% endfor %}

```

I already saw this simple blog feature in "build flask blog"-tutorials but I'm not experienced enought to just implement it.

> Could you give an example of where you would see the switch? i.e. env variable or as part of the metadata?

maybe in metadata. Something like `showEntry` that defaults to TRUE and can be set to FALSE to exclude it from the nav.


Maybe it's easy to implement, maybe not. I'll use it anyways ;D




> Just out of curiosity, how did you hear about Docnado? :)

Looooots of googeling. I tried everything and finally found your entry in [Awesome Static Web Site Generators](https://github.com/myles/awesome-static-generators)(thank god that @JohnHardy  it there!).

I tried lot's of systems (end even build one with exaclty the mentioned "[many files one page"-feature myself](https://github.com/6uhrmittag/bashblog)) but docnado looks like the simplest "just start writing" solution! It's awesome :thumbsup: thank you for publishing it!

**Comment by JohnHardy** [comment]
Perfect! Having the software and config get out of the way and "just starting writing" is our bag!

I see!  We didn't intend docnado to be a blog-style system, so I struggle to see a natural fit without adding edge-cases.  However...

We could implement an `include` markdown tag, like: `![](myfile.md)`.  This would let you inject a series of documents within a document.  I think that would be kind of messy though.

Alternatively, a meta-data tag like: `post_include:  *.md` could search and render all markdown files below the content of this document.  It could get recursive if we are not careful!

Thanks very much for implementing the `tox` and test cases by the way.  That is awesome of you 👍 🥇

**Comment by 6uhrmittag** [comment]
> I see! We didn't intend docnado to be a blog-style system, so I struggle to see a natural fit without adding edge-cases. However...

No worries, totally get it. It shouldn't influence the usability and it'd probably feel strange. 
(and since it looks like more work then I thought, you can probably close this issue then)

> Thanks very much for implementing the tox and test cases by the way. 

You're welcome! Check out [cookiecutter-pypackage](https://github.com/audreyr/cookiecutter-pypackage) in case you're interested in more features. It provides templates for tests, auto-deployment to pypi and readthedocs. I used it to enhance [taskbutler](https://github.com/6uhrmittag/taskbutler) and the workflow CI -> pypi

**Comment by JohnHardy** [comment]
Ok cool, I'll keep it in mind for the future.

Thanks! Will do!
